version: "3.9"

services:
  db:
    image: supabase/postgres:17.6.1.136
    container_name: supabase-db
    restart: unless-stopped

    env_file:
      - .env

    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}

    volumes:
      - ./volumes/db:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  studio:
    image: supabase/studio:2026.06.03-sha-0bca601
    container_name: supabase-studio
    restart: unless-stopped

    env_file:
      - .env

    depends_on:
      db:
        condition: service_healthy

    environment:
      STUDIO_PG_META_URL: http://meta:8080
      DEFAULT_ORGANIZATION_NAME: Leonet
      DEFAULT_PROJECT_NAME: Production

    ports:
      - "3000:3000"

  meta:
    image: supabase/postgres-meta:v0.96.6
    container_name: supabase-meta
    restart: unless-stopped

    env_file:
      - .env

    depends_on:
      db:
        condition: service_healthy

    environment:
      PG_META_PORT: 8080

      PG_META_DB_HOST: db
      PG_META_DB_NAME: ${POSTGRES_DB}
      PG_META_DB_PORT: 5432
      PG_META_DB_USER: ${POSTGRES_USER}
      PG_META_DB_PASSWORD: ${POSTGRES_PASSWORD}
